src/Sylius/Bundle/WebBundle/Form/ProfileFormType.php
<?php

/*
 * This file is part of the Sylius package.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sylius\Bundle\WebBundle\Form;

use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Profile form.
 *
 * @author Julien Janvier <j.janvier@gmail.com>
 */
class ProfileFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName', 'text', array(
                'label'    => 'sylius.form.profile.firstName'
            ))
            ->add('lastName', 'text', array(
                'label'    => 'sylius.form.profile.lastName'
            ))
            ->add('email', 'email', array(
                'label'    => 'sylius.form.profile.email'
            ))
        ;
    }

    public function getName()
    {
        return 'sylius_user_profile';
    }
}

src/Sylius/Bundle/WebBundle/Controller/Backend/DashboardController.php
<?php

/*
 * This file is part of the Sylius package.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sylius\Bundle\WebBundle\Controller\Backend;

use Sylius\Component\Order\Model\OrderInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Backend dashboard controller.
 *
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 */
class DashboardController extends Controller
{
    /**
     * Backend dashboard display action.
     */
    public function mainAction()
    {
        $orderRepository = $this->get('sylius.repository.order');
        $userRepository  = $this->get('sylius.repository.user');

        return $this->render('SyliusWebBundle:Backend/Dashboard:main.html.twig', array(
            'orders_count'        => $orderRepository->countBetweenDates(new \DateTime('1 month ago'), new \DateTime()),
            'orders'              => $orderRepository->findBy(array(), array('updatedAt' => 'desc'), 5),
            'users'               => $userRepository->findBy(array(), array('id' => 'desc'), 5),
            'registrations_count' => $userRepository->countBetweenDates(new \DateTime('1 month ago'), new \DateTime()),
            'sales'               => $orderRepository->revenueBetweenDates(new \DateTime('1 month ago'), new \DateTime()),
            'sales_confirmed'     => $orderRepository->revenueBetweenDates(new \DateTime('1 month ago'), new \DateTime(), OrderInterface::STATE_CONFIRMED),
        ));
    }
}

src/Sylius/Bundle/WebBundle/Controller/Backend/FormController.php
<?php

/*
 * This file is part of the Sylius package.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sylius\Bundle\WebBundle\Controller\Backend;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * Backend forms controller.
 *
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 * @author Saša Stamenković <umpirsky@gmail.com>
 */
class FormController extends Controller
{
    /**
     * @param string $type
     * @param string $template
     *
     * @return Response
     */
    public function showAction($type, $template)
    {
        return $this->render($template, array(
            'form' => $this->createForm($type)->createView()
        ));
    }

    /**
     * Render filter form.
     *
     * @param string $type
     * @param string $template
     *
     * @return Response
     */
    public function filterAction($type, $template = 'SyliusWebBundle:Backend/Form:filter.html.twig')
    {
        return $this->render($template, array(
            'form' => $this->get('form.factory')->createNamed('criteria', $type)->createView()
        ));
    }
}

src/Sylius/Bundle/WebBundle/Controller/Backend/SecurityController.php
<?php

/*
 * This file is part of the Sylius package.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sylius\Bundle\WebBundle\Controller\Backend;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * Backend security controller.
 *
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 */
class SecurityController extends Controller
{
    /**
     * Target action for _switch_user=_exit, redirects admin back to impersonated user
     *
     * @param string $username
     *
     * @return RedirectResponse
     *
     * @throws AccessDeniedException
     * @throws NotFoundHttpException
     */
    public function exitUserSwitchAction($username)
    {
        if (!$this->get('security.context')->isGranted('ROLE_SYLIUS_ADMIN')) {
            throw new AccessDeniedException();
        }

        $user = $this->get('sylius.repository.user')->findOneBy(array('usernameCanonical' => $username));

        if (!$user) {
            throw new NotFoundHttpException(sprintf('User with username %s does not exist.', $username));
        }

        return $this->redirect($this->generateUrl('sylius_backend_user_show', array('id' => $user->getId())));
    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function loginAction(Request $request)
    {
        $session = $request->getSession();
        $error = null;

        if ($request->attributes->has(SecurityContext::AUTHENTICATION_ERROR)) {
            $error = $request->attributes->get(SecurityContext::AUTHENTICATION_ERROR);
        } elseif (null !== $session && $session->has(SecurityContext::AUTHENTICATION_ERROR)) {
            $error = $session->get(SecurityContext::AUTHENTICATION_ERROR);
            $session->remove(SecurityContext::AUTHENTICATION_ERROR);
        }

        if ($error) {
            $error = $error->getMessage();
        }

        $lastUsername = (null === $session) ? '' : $session->get(SecurityContext::LAST_USERNAME);

        $csrfToken = $this
            ->getFormCsrfProvider()
            ->generateCsrfToken('authenticate')
        ;

        return $this->render('SyliusWebBundle:Backend/Security:login.html.twig', array(
            'last_username' => $lastUsername,
            'error'         => $error,
            'token'         => $csrfToken,
        ));
    }

    public function checkAction()
    {
        throw new \RuntimeException('You must configure the check path to be handled by the firewall.');
    }

    public function logoutAction()
    {
        throw new \RuntimeException('You must activate the logout in your security firewall configuration');
    }

    private function getFormCsrfProvider()
    {
        return $this->get('form.csrf_provider');
    }
}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/_form.html.twig
{% form_theme form 'SyliusWebBundle::forms.html.twig' %}

<fieldset>
    {{ form_row(form.category) }}
    {{ form_row(form.zone) }}
    {{ form_row(form.name) }}
    {{ form_row(form.amount) }}
    {{ form_row(form.includedInPrice) }}
    {{ form_row(form.calculator) }}
</fieldset>

{{ form_rest(form) }}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/create.html.twig
{% extends 'SyliusWebBundle:Backend:layout.html.twig' %}

{% from 'SyliusResourceBundle:Macros:actions.html.twig' import create %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'sylius.breadcrumb.configuration'|trans }}</li>
    <li><a href="{{ path('sylius_backend_tax_rate_index') }}">{{ 'sylius.breadcrumb.tax_rate.index'|trans }}</a></li>
    <li>{{ 'sylius.breadcrumb.new'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <h1><i class="glyphicon glyphicon-plus-sign"></i> {{ 'sylius.tax_rate.create_header'|trans|raw }}</h1>
</div>

{{ form_errors(form) }}

<form action="{{ path('sylius_backend_tax_rate_create') }}" method="post" class="form-horizontal" novalidate>
    {% include 'SyliusWebBundle:Backend/TaxRate:_form.html.twig' %}
    {{ create() }}
</form>
{% endblock %}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/index.html.twig
{% extends 'SyliusWebBundle:Backend:layout.html.twig' %}

{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}
{% from 'SyliusWebBundle:Backend/Macros:misc.html.twig' import pagination %}
{% from 'SyliusWebBundle:Backend/TaxRate:macros.html.twig' import list %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'sylius.breadcrumb.configuration'|trans }}</li>
    <li>{{ 'sylius.breadcrumb.tax_rate.index'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="actions-menu">
        {{ buttons.create(path('sylius_backend_tax_rate_create'), 'sylius.tax_rate.create'|trans) }}
        {{ buttons.manage(path('sylius_backend_tax_category_index'), 'sylius.tax_category.manage'|trans) }}
    </div>
    <h1><i class="glyphicon glyphicon-cog"></i> {{ 'sylius.tax_rate.index_header'|trans|raw }}</h1>
</div>


{{ pagination(tax_rates) }}
{{ list(tax_rates) }}
{{ pagination(tax_rates) }}

{% endblock %}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/macros.html.twig
{% macro list(tax_rates) %}

{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}
{% import 'SyliusWebBundle:Backend/Macros:alerts.html.twig' as alerts %}
{% import 'SyliusWebBundle:Backend/Macros:misc.html.twig' as misc %}

{% if tax_rates|length > 0 %}
<table class="table">
    <thead>
        <tr>
            <th>{{ sylius_resource_sort('id', '#id') }}</th>
            <th>{{ sylius_resource_sort('category', 'sylius.tax_rate.category'|trans) }}</th>
            <th>{{ sylius_resource_sort('zone', 'sylius.tax_rate.zone'|trans) }}</th>
            <th>{{ sylius_resource_sort('name', 'sylius.tax_rate.name'|trans) }}</th>
            <th>{{ sylius_resource_sort('amount', 'sylius.tax_rate.amount'|trans) }}</th>
            <th>{{ sylius_resource_sort('includedInPrice', 'sylius.tax_rate.included_in_price'|trans) }}</th>
            <th>{{ sylius_resource_sort('calculator', 'sylius.tax_rate.calculator'|trans) }}</th>
            <th>{{ sylius_resource_sort('updatedAt', 'sylius.tax_rate.updated_at'|trans) }}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for tax_rate in tax_rates %}
        <tr id="{{ tax_rate.id }}">
            <td>{{ tax_rate.id }}</td>
            <td>{{ tax_rate.category }}</td>
            <td>{{ tax_rate.zone }}</td>
            <td>{{ tax_rate.name }}</td>
            <td>{{ tax_rate.amountAsPercentage }}%</td>
            <td>
                {{ misc.state_label(tax_rate.includedInPrice) }}
            </td>
            <td><span class="label label-primary">{{ tax_rate.calculator|humanize|upper }}</span></td>
            <td>{{ tax_rate.updatedAt|date }}</td>
            <td>
                <div class="pull-right">
                {{ buttons.show(path('sylius_backend_tax_rate_show', {'id': tax_rate.id})) }}
                {{ buttons.edit(path('sylius_backend_tax_rate_update', {'id': tax_rate.id})) }}
                {{ buttons.delete(path('sylius_backend_tax_rate_delete', {'id': tax_rate.id})) }}
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
{{ alerts.info('sylius.tax_rate.no_results'|trans) }}
{% endif %}

{% endmacro %}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/show.html.twig
{% extends 'SyliusWebBundle:Backend:layout.html.twig' %}
{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'sylius.breadcrumb.configuration'|trans }}</li>
    <li><a href="{{ path('sylius_backend_tax_rate_index') }}">{{ 'sylius.breadcrumb.tax_rate.index'|trans }}</a></li>
    <li>{{ tax_rate.name }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
<h1>{{ 'sylius.tax_rate.show_header'|trans|raw }}</h1>
</div>

<div class="well">
    <a href="{{ path('sylius_backend_tax_rate_index') }}" class="btn btn-primary">
        <i class="glyphicon glyphicon-list-alt"></i> {{ 'sylius.tax_rate.manage'|trans }}
    </a>
    <a href="{{ path('sylius_backend_tax_rate_update', {'id': tax_rate.id}) }}" class="btn">
        <i class="glyphicon glyphicon-pencil"></i> {{ 'sylius.edit'|trans }}
    </a>
    {{ buttons.delete(path('sylius_backend_tax_rate_delete', {'id': tax_rate.id})) }}
</div>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>{{ 'sylius.tax_rate.category'|trans }}</th>
            <th>{{ 'sylius.tax_rate.name'|trans }}</th>
            <th>{{ 'sylius.tax_rate.zone'|trans }}</th>
            <th>{{ 'sylius.tax_rate.amount'|trans }}</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ tax_rate.category }}</td>
            <td>{{ tax_rate.name }}</td>
            <td>{{ tax_rate.zone }}</td>
            <td>{{ tax_rate.amountAsPercentage }}%</td>
        </tr>
    </tbody>
</table>
{% endblock %}

src/Sylius/Bundle/WebBundle/Resources/views/Backend/TaxRate/update.html.twig
{% extends 'SyliusWebBundle:Backend:layout.html.twig' %}

{% from 'SyliusResourceBundle:Macros:actions.html.twig' import update %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'sylius.breadcrumb.configuration'|trans }}</li>
    <li><a href="{{ path('sylius_backend_tax_rate_index') }}">{{ 'sylius.breadcrumb.tax_rate.index'|trans }}</a></li>
    <li><a href="{{ path('sylius_backend_tax_rate_show', {'id': tax_rate.id}) }}">{{ tax_rate.name }}</a></li>
    <li>{{ 'sylius.breadcrumb.edit'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <h1><i class="glyphicon glyphicon-pencil"></i> {{ 'sylius.tax_rate.update_header'|trans|raw }}</h1>
</div>

{{ form_errors(form) }}

<form action="{{ path('sylius_backend_tax_rate_update', {'id': tax_rate.id}) }}" method="post" class="form-horizontal" novalidate>
    <input type="hidden" name="_method" value="PUT">
    {% include 'SyliusWebBundle:Backend/TaxRate:_form.html.twig' %}
    {{ update() }}
</form>
{% endblock %}